name: Pub Publish dry run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Pub publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Dart pub get
        run: dart pub get --no-example

      - name: Test
        if: ${{ hashFiles('test/**') != '' }}
        run: flutter test --no-pub

      - name: Publish dry run
        run: dart pub publish --dry-run
