name: Pub Publish dry run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Dry run
        uses: k-paxian/dart-package-publisher@532e6f31bf6171f0043d3ff5fa31437afe5249c2
        with:
          credentialJson: 'MockCredentialJson'
          flutter: true
          dryRunOnly: true
          skipTests: true
